/*
 * This file is generated by jOOQ.
 */
package com.example.multipledatabasesmultipleconnections.jooq.db.public_;


import com.example.multipledatabasesmultipleconnections.jooq.db.public_.tables.Author;
import com.example.multipledatabasesmultipleconnections.jooq.db.public_.tables.Book;
import com.example.multipledatabasesmultipleconnections.jooq.db.public_.tables.BookStore;
import com.example.multipledatabasesmultipleconnections.jooq.db.public_.tables.BookToBookStore;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PK_T_AUTHOR = Indexes0.PK_T_AUTHOR;
    public static final Index PK_T_BOOK = Indexes0.PK_T_BOOK;
    public static final Index UK_T_BOOK_STORE_NAME = Indexes0.UK_T_BOOK_STORE_NAME;
    public static final Index PK_B2BS = Indexes0.PK_B2BS;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PK_T_AUTHOR = Internal.createIndex("pk_t_author", Author.AUTHOR, new OrderField[] { Author.AUTHOR.ID }, true);
        public static Index PK_T_BOOK = Internal.createIndex("pk_t_book", Book.BOOK, new OrderField[] { Book.BOOK.ID }, true);
        public static Index UK_T_BOOK_STORE_NAME = Internal.createIndex("uk_t_book_store_name", BookStore.BOOK_STORE, new OrderField[] { BookStore.BOOK_STORE.NAME }, true);
        public static Index PK_B2BS = Internal.createIndex("pk_b2bs", BookToBookStore.BOOK_TO_BOOK_STORE, new OrderField[] { BookToBookStore.BOOK_TO_BOOK_STORE.BOOK_STORE_NAME, BookToBookStore.BOOK_TO_BOOK_STORE.BOOK_ID }, true);
    }
}
