/*
 * This file is generated by jOOQ.
 */
package com.example.multipledatabasesmultipleconnections.jooq.db.public_;


import com.example.multipledatabasesmultipleconnections.jooq.db.public_.tables.Author;
import com.example.multipledatabasesmultipleconnections.jooq.db.public_.tables.Book;
import com.example.multipledatabasesmultipleconnections.jooq.db.public_.tables.BookStore;
import com.example.multipledatabasesmultipleconnections.jooq.db.public_.tables.BookToBookStore;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>public.book</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>public.book_store</code>.
     */
    public static final BookStore BOOK_STORE = BookStore.BOOK_STORE;

    /**
     * The table <code>public.book_to_book_store</code>.
     */
    public static final BookToBookStore BOOK_TO_BOOK_STORE = BookToBookStore.BOOK_TO_BOOK_STORE;
}
