/*
 * This file is generated by jOOQ.
 */
package com.example.multipledatabasesmultipleconnections.jooq.mysqljooq.mysqljooq;


import com.example.multipledatabasesmultipleconnections.jooq.mysqljooq.DefaultCatalog;
import com.example.multipledatabasesmultipleconnections.jooq.mysqljooq.mysqljooq.tables.Student;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mysqljooq extends SchemaImpl {

    private static final long serialVersionUID = 10604995;

    /**
     * The reference instance of <code>mysqljooq</code>
     */
    public static final Mysqljooq MYSQLJOOQ = new Mysqljooq();

    /**
     * The table <code>mysqljooq.student</code>.
     */
    public final Student STUDENT = com.example.multipledatabasesmultipleconnections.jooq.mysqljooq.mysqljooq.tables.Student.STUDENT;

    /**
     * No further instances allowed
     */
    private Mysqljooq() {
        super("mysqljooq", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Student.STUDENT);
    }
}
