/*
 * This file is generated by jOOQ.
 */
package com.example.multipledatabasesmultipleconnections.jooq.mysqljooq.mysqljooq;


import com.example.multipledatabasesmultipleconnections.jooq.mysqljooq.mysqljooq.tables.Student;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in mysqljooq
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>mysqljooq.student</code>.
     */
    public static final Student STUDENT = Student.STUDENT;
}
